# Generated by Django 5.1.1 on 2024-09-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit_history',
            name='visit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
