# Generated by Django 5.1.1 on 2024-09-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='place',
            name='number_of_ratings',
        ),
    ]
