# Generated by Django 5.1.1 on 2024-09-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0002_alter_visit_history_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit_history',
            name='times_visited',
        ),
        migrations.AlterField(
            model_name='visit_history',
            name='visit_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
