# Generated by Django 5.1.1 on 2024-10-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0003_remove_visit_history_times_visited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
