# Generated by Django 5.1.1 on 2024-10-06 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0005_user_born_day_user_geneder_user_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='geneder',
            new_name='gender',
        ),
    ]
