# Generated by Django 5.1.1 on 2024-10-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0006_rename_geneder_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
