# Generated by Django 5.1.1 on 2024-10-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tour', '0007_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.TextField(blank=True, null=True),
        ),
    ]
